name: go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.x'
      - name: build
        run: make build
      - name: test
        run: make test
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.58
          skip-pkg-cache: true
